=== padenot/usdp/rsase/SGBag/exec/sgbag-schema.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT config ((noeud|troncon)+,(tapis|toboggan)+,chariot+)>
<!ATTLIST config
  xmlns CDATA #FIXED ''>

<!ELEMENT noeud (id,x,y,suivantGauche,suivantDroit?)>
<!ATTLIST noeud
  xmlns CDATA #FIXED ''>

<!ELEMENT troncon (id,noeudDebut,noeudFin)>
<!ATTLIST troncon
  xmlns CDATA #FIXED ''>

<!ELEMENT tapis (id,x,y,pos)>
<!ATTLIST tapis
  xmlns CDATA #FIXED ''>

<!ELEMENT toboggan (id,x,y,pos)>
<!ATTLIST toboggan
  xmlns CDATA #FIXED ''>

<!ELEMENT chariot (id,pos,tapisAssocie)>
<!ATTLIST chariot
  xmlns CDATA #FIXED ''>

<!ELEMENT suivantGauche (#PCDATA)>
<!ATTLIST suivantGauche
  xmlns CDATA #FIXED ''>

<!ELEMENT suivantDroit (#PCDATA)>
<!ATTLIST suivantDroit
  xmlns CDATA #FIXED ''>

<!ELEMENT noeudDebut (#PCDATA)>
<!ATTLIST noeudDebut
  xmlns CDATA #FIXED ''>

<!ELEMENT noeudFin (#PCDATA)>
<!ATTLIST noeudFin
  xmlns CDATA #FIXED ''>

<!ELEMENT tapisAssocie (#PCDATA)>
<!ATTLIST tapisAssocie
  xmlns CDATA #FIXED ''>

<!ELEMENT id (#PCDATA)>
<!ATTLIST id
  xmlns CDATA #FIXED ''>

<!ELEMENT x (#PCDATA)>
<!ATTLIST x
  xmlns CDATA #FIXED ''>

<!ELEMENT y (#PCDATA)>
<!ATTLIST y
  xmlns CDATA #FIXED ''>

<!ELEMENT pos (#PCDATA)>
<!ATTLIST pos
  xmlns CDATA #FIXED ''>

=== padenot/usdp/rsase/SGBag/exec/configuration_decoupee.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "sgbag-schema.dtd">
<!--
 * Configuration complexe de l'aéroport
 * 2 tapis, 2 tobogans.
-->
<config>
  <!-- Circuit A -->
	<!-- Colone 1 x = 10 -->
	<noeud>
		<id>1</id>
		<x>10</x>
		<y>100</y>
		<suivantGauche>9</suivantGauche>
	</noeud>
	<noeud>
		<id>2</id>
		<x>10</x>
		<y>200</y>
		<suivantGauche>4244</suivantGauche>
	</noeud>
	<noeud>
		<id>3</id>
		<x>10</x>
		<y>300</y>
		<suivantGauche>4254</suivantGauche>
	</noeud>
	<troncon>
		<id>4</id>
		<noeudDebut>2</noeudDebut>
		<noeudFin>4243</noeudFin>
	</troncon>
	<troncon>
		<id>5</id>
		<noeudDebut>3</noeudDebut>
		<noeudFin>4253</noeudFin>
	</troncon>
	<troncon>
		<id>72</id>
		<noeudDebut>2</noeudDebut>
		<noeudFin>1</noeudFin>
	</troncon>
	<!-- Col 2 x = 20 -->
	<noeud>
		<id>6</id>
		<x>20</x>
		<y>90</y>
		<suivantGauche>13</suivantGauche>
	</noeud>
	<noeud>
		<id>7</id>
		<x>20</x>
		<y>210</y>
		<suivantGauche>10</suivantGauche>
	</noeud>
	<noeud>
		<id>8</id>
		<x>20</x>
		<y>310</y>
		<suivantGauche>11</suivantGauche>
	</noeud>
	<troncon>
		<id>9</id>
		<noeudDebut>1</noeudDebut>
		<noeudFin>6</noeudFin>
	</troncon>
	<troncon>
		<id>10</id>
		<noeudDebut>7</noeudDebut>
		<noeudFin>2</noeudFin>
	</troncon>
	<troncon>
		<id>11</id>
		<noeudDebut>8</noeudDebut>
		<noeudFin>3</noeudFin>
	</troncon>
	<!-- Colone 3  x = 40 -->
	<noeud>
		<id>12</id>
		<x>40</x>
		<y>90</y>
		<suivantGauche>42344</suivantGauche>
		<suivantDroit>34</suivantDroit>
	</noeud>
	<troncon>
		<id>13</id>
		<noeudDebut>6</noeudDebut>
		<noeudFin>12</noeudFin>
	</troncon>
	<!-- Colone 4 x = 50 -->
	<noeud>
		<id>14</id>
		<x>50</x>
		<y>80</y>
		<suivantGauche>19</suivantGauche>
	</noeud>
	<noeud>
		<id>15</id>
		<x>50</x>
		<y>310</y>
		<suivantGauche>17</suivantGauche>
	</noeud>
	<troncon>
		<id>16</id>
		<noeudDebut>12</noeudDebut>
		<noeudFin>14</noeudFin>
	</troncon>
	<troncon>
		<id>17</id>
		<noeudDebut>15</noeudDebut>
		<noeudFin>8</noeudFin>
	</troncon>
	<!-- Colone 5 x = 60 -->
	<noeud>
		<id>18</id>
		<x>60</x>
		<y>80</y>
		<suivantGauche>21</suivantGauche>
	</noeud>
	<troncon>
		<id>19</id>
		<noeudDebut>14</noeudDebut>
		<noeudFin>18</noeudFin>
	</troncon>
	<!-- Colone 6 x = 70 -->
	<noeud>
		<id>20</id>
		<x>70</x>
		<y>80</y>
		<suivantGauche>23</suivantGauche>
	</noeud>
	<troncon>
		<id>21</id>
		<noeudDebut>18</noeudDebut>
		<noeudFin>20</noeudFin>
	</troncon>
	<!-- Colone 7 x = 130 -->
	<noeud>
		<id>22</id>
		<x>80</x> <!-- déplacement du tapis -->
		<y>80</y>
		<suivantGauche>25</suivantGauche>
	</noeud>
	<troncon>
		<id>23</id>
		<noeudDebut>20</noeudDebut>
		<noeudFin>22</noeudFin>
	</troncon>
	<!-- colone 8 x=140 -->
	<noeud>
		<id>24</id>
		<x>90</x>
		<y>80</y>
		<suivantGauche>28</suivantGauche>
	</noeud>
	<troncon>
		<id>25</id>
		<noeudDebut>22</noeudDebut>
		<noeudFin>24</noeudFin>
	</troncon>
	<!-- Colone 9 x=150 -->
	<noeud>
		<id>26</id>
		<x>150</x>
		<y>80</y>
		<suivantGauche>33</suivantGauche>
	</noeud>
	<noeud>
		<id>27</id>
		<x>150</x>
		<y>210</y>
		<suivantGauche>42304</suivantGauche>
		<suivantDroit>30</suivantDroit>
	</noeud>
	<troncon>
		<id>28</id>
		<noeudDebut>24</noeudDebut>
		<noeudFin>26</noeudFin>
	</troncon>
	<troncon>
		<id>29</id>
		<noeudDebut>27</noeudDebut>
		<noeudFin>42293</noeudFin>
	</troncon>
	<troncon>
		<id>30</id>
		<noeudDebut>27</noeudDebut>
		<noeudFin>42303</noeudFin>
	</troncon>
	<!-- Colone 10 x=160 -->
	<noeud>
		<id>31</id>
		<x>160</x>
		<y>90</y>
		<suivantGauche>43</suivantGauche>
		<!-- Jointure Circuit B -->
		<suivantDroit>38</suivantDroit>
	</noeud>
	<noeud>
		<id>32</id>
		<x>160</x>
		<y>210</y>
		<suivantGauche>35</suivantGauche>
	</noeud>
	<troncon>
		<id>33</id>
		<noeudDebut>26</noeudDebut>
		<noeudFin>31</noeudFin>
	</troncon>
	<troncon>
		<id>34</id>
		<noeudDebut>12</noeudDebut>
		<noeudFin>42343</noeudFin>
	</troncon>
	<troncon>
		<id>35</id>
		<noeudDebut>32</noeudDebut>
		<noeudFin>27</noeudFin>
	</troncon>
	<!-- Colone 11 x=170 -->
	<noeud>
		<id>36</id>
		<x>170</x>
		<y>100</y>
		<suivantGauche>42394</suivantGauche>
	</noeud>
	<noeud>
		<id>37</id>
		<x>170</x>
		<y>200</y>
		<suivantGauche>40</suivantGauche>
	</noeud>
	<troncon>
		<id>38</id>
		<noeudDebut>31</noeudDebut>
		<noeudFin>36</noeudFin>
	</troncon>
	<troncon>
		<id>39</id>
		<noeudDebut>36</noeudDebut>
		<noeudFin>42393</noeudFin>
	</troncon>
	<troncon>
		<id>40</id>
		<noeudDebut>37</noeudDebut>
		<noeudFin>32</noeudFin>
	</troncon>
  <!-- Circuit B TODO-->
	<!-- Colone 12 x=180 -->
	<noeud>
		<id>41</id>
		<x>180</x>
		<y>90</y>
		<suivantGauche>46</suivantGauche>
		<suivantDroit>61</suivantDroit>
	</noeud>
	<noeud>
		<id>42</id>
		<x>180</x>
		<y>310</y>
		<suivantGauche>42444</suivantGauche>
	</noeud>
	<troncon>
		<id>43</id>
		<noeudDebut>31</noeudDebut>
		<noeudFin>41</noeudFin>
	</troncon>
	<troncon>
		<id>44</id>
		<noeudDebut>42</noeudDebut>
		<noeudFin>42443</noeudFin>
	</troncon>
	<!-- Colone 13 x=190 -->
	<noeud>
		<id>45</id>
		<x>190</x>
		<y>80</y>
		<suivantGauche>48</suivantGauche>
	</noeud>
	<troncon>
		<id>46</id>
		<noeudDebut>41</noeudDebut>
		<noeudFin>45</noeudFin>
	</troncon>
	<!-- Colone 14 x=200 -->
	<noeud>
		<id>47</id>
		<x>200</x>
		<y>80</y>
		<suivantGauche>51</suivantGauche>
	</noeud>
	<troncon>
		<id>48</id>
		<noeudDebut>45</noeudDebut>
		<noeudFin>47</noeudFin>
	</troncon>
	<!-- Colone 15 x=210 -->
	<noeud>
		<id>49</id>
		<x>210</x>
		<y>80</y>
		<suivantGauche>54</suivantGauche>
	</noeud>
	<noeud>
		<id>50</id>
		<x>210</x>
		<y>310</y>
		<suivantGauche>52</suivantGauche>
	</noeud>
	<troncon>
		<id>51</id>
		<noeudDebut>47</noeudDebut>
		<noeudFin>49</noeudFin>
	</troncon>
	<troncon>
		<id>52</id>
		<noeudDebut>50</noeudDebut>
		<noeudFin>42</noeudFin>
	</troncon>
	<!-- Colone 16 x=270 -->
	<noeud>
		<id>53</id>
		<x>220</x>
		<y>80</y>
		<suivantGauche>56</suivantGauche>
	</noeud>
	<troncon>
		<id>54</id>
		<noeudDebut>49</noeudDebut>
		<noeudFin>53</noeudFin>
	</troncon>
	<!-- Colone 17 x=280 -->
	<noeud>
		<id>55</id>
		<x>230</x>
		<y>80</y>
		<suivantGauche>58</suivantGauche>
	</noeud>
	<troncon>
		<id>56</id>
		<noeudDebut>53</noeudDebut>
		<noeudFin>55</noeudFin>
	</troncon>
	<!--  Colone 18 x=290 -->
	<noeud>
		<id>57</id>
		<x>290</x>
		<y>80</y>
		<suivantGauche>60</suivantGauche>
	</noeud>
	<troncon>
		<id>58</id>
		<noeudDebut>55</noeudDebut>
		<noeudFin>57</noeudFin>
	</troncon>
	<!-- Colone 19 x=300 -->
	<noeud>
		<id>59</id>
		<x>300</x>
		<y>90</y>
		<suivantGauche>64</suivantGauche>
	</noeud>
	<troncon>
		<id>60</id>
		<noeudDebut>57</noeudDebut>
		<noeudFin>59</noeudFin>
	</troncon>
	<troncon>
		<id>61</id>
		<noeudDebut>41</noeudDebut>
		<noeudFin>59</noeudFin>
	</troncon>
	<!-- Colone 20 x=310 -->
	<noeud>
		<id>62</id>
		<x>310</x>
		<y>90</y>
		<suivantGauche>69</suivantGauche>
	</noeud>
	<noeud>
		<id>63</id>
		<x>310</x>
		<y>210</y>
		<suivantGauche>42664</suivantGauche>
		<suivantDroit>66</suivantDroit>
	</noeud>
	<troncon>
		<id>64</id>
		<noeudDebut>59</noeudDebut>
		<noeudFin>62</noeudFin>
	</troncon>
	<troncon>
		<id>65</id>
		<noeudDebut>63</noeudDebut>
		<!-- Jointure circuit A -->
		<noeudFin>42653</noeudFin>
	</troncon>
	<troncon>
		<id>66</id>
		<noeudDebut>63</noeudDebut>
		<noeudFin>42663</noeudFin>
	</troncon>
	<!-- Colone 21 x=320 -->
	<noeud>
		<id>67</id>
		<x>320</x>
		<y>100</y>
		<suivantGauche>42704</suivantGauche>
	</noeud>
	<noeud>
		<id>68</id>
		<x>320</x>
		<y>200</y>
		<suivantGauche>71</suivantGauche>
	</noeud>
	<troncon>
		<id>69</id>
		<noeudDebut>62</noeudDebut>
		<noeudFin>67</noeudFin>
	</troncon>
	<troncon>
		<id>70</id>
		<noeudDebut>67</noeudDebut>
		<noeudFin>42703</noeudFin>
	</troncon>
	<troncon>
		<id>71</id>
		<noeudDebut>68</noeudDebut>
		<noeudFin>63</noeudFin>
	</troncon>
  <!-- Objets -->
  	<!-- A -->
  	<tapis>
  		<id>101</id>
  		<x>120</x>
  		<y>50</y>
  		<pos>28</pos>
  	</tapis>
	<toboggan>
		<id>102</id>
		<x>35</x>
		<y>340</y>
		<pos>17</pos>
	</toboggan>
	<!-- B -->
	<tapis>
		<id>103</id>
		<x>260</x>
		<y>50</y>
		<pos>58</pos>
	</tapis>
	<toboggan>
		<id>104</id>
		<x>195</x>
		<y>340</y>
		<pos>52</pos>
	</toboggan>
	
	<!-- Chariots -->
	<!-- A vers A -->
	<chariot>
		<id>201</id>
		<pos>39</pos>
		<tapisAssocie>101</tapisAssocie>
	</chariot>
	<chariot>
		<id>202</id>
		<pos>11</pos>
		<tapisAssocie>101</tapisAssocie>
	</chariot>
	
	<!-- B vers B -->
	<chariot>
		<id>203</id>
		<pos>69</pos>
		<tapisAssocie>103</tapisAssocie>
	</chariot>
	<chariot>
		<id>204</id>
		<pos>52</pos>
		<tapisAssocie>103</tapisAssocie>
	</chariot>
	
	<!-- B vers A -->
	<chariot>
		<id>205</id>
		<pos>71</pos>
		<tapisAssocie>101</tapisAssocie>
	</chariot>
	
	<chariot>
		<id>206</id>
		<pos>61</pos>
		<tapisAssocie>101</tapisAssocie>
	</chariot>
	
	<!-- A vers B -->
	<chariot>
		<id>207</id>
		<pos>29</pos>
		<tapisAssocie>103</tapisAssocie>
	</chariot>
	<chariot>
		<id>208</id>
		<pos>9</pos>
		<tapisAssocie>103</tapisAssocie>
	</chariot>
